# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Activator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
print("1")
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
print("2")

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(331, 151)
        Window.setStyleSheet("background-color:rgb(52, 52, 52)")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.ActBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ActBtn.setGeometry(QtCore.QRect(10, 80, 311, 51))
        self.ActBtn.setStyleSheet("\n"
".QPushButton{\n"
"color:white;\n"
"border-radius: 10px;\n"
"border: 3px solid rgb(35, 35, 35);\n"
"font: 63 18pt \"Yu Gothic UI\";\n"
"}\n"
".QPushButton:hover{\n"
"border-radius: 15px;\n"
"background-color:rgb(67, 67, 67);\n"
"}\n"
".QPushButton:press{\n"
"backgrond-color:rgb(0, 213, 0)\n"
"}\n"
"QPushButton:hover:pressed\n"
"{\n"
"  \n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ActBtn.setObjectName("ActBtn")
        self.ChangeVer = QtWidgets.QComboBox(self.centralwidget)
        self.ChangeVer.setGeometry(QtCore.QRect(30, 20, 271, 41))
        self.ChangeVer.setStyleSheet(".QComboBox{\n"
"background-color: rgb(95, 95, 95);\n"
"border: 3px solid rgb(234, 234, 234);\n"
"border-radius:10px;\n"
"text-align: center;\n"
"color: white;\n"
"font: 75 14pt \"Yu Gothic UI\";\n"
"}\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"    text-align: center;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"  color:white;    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"    text-align: center;\n"
"}\n"
"QComboBox:hover{\n"
"background-color: rgb(208, 208, 208);\n"
"}")
        self.ChangeVer.setObjectName("ChangeVer")
        self.ChangeVer.addItem("")
        self.ChangeVer.addItem("")
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Activator"))
        self.ActBtn.setText(_translate("Window", "Активировать"))
        self.ChangeVer.setItemText(0, _translate("Window", "Windows 10/11 Pro"))
        self.ChangeVer.setItemText(1, _translate("Window", "Windows 10 LTSC/LTSB"))
